name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Run checks
      run: npm run check:all
      
    - name: Build project
      run: npm run build-for-deploy
      
    - name: Deploy to FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ie.kernich.de
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localDir: dist
        remoteDir: ui5-fontawesome-lib